//
//  UXRGlobals.m
//  FMag
//
//  Created by Rex St. John on 12/20/13.
//  Copyright (c) 2013 UX-RX. All rights reserved.
//

#import "UXRGlobals.h"

@implementation UXRGlobals

const NSString* FOURSQUARE_CLIENT_ID = @"XXX";
const NSString* FOURSQUARE_SECRET = @"XXX";
const NSString* FOURSQUARE_CALLBACK_URL = @"fmag://foursquare";

//
const NSString* MAIN_STORYBOARD_ID = @"Storyboard";

//
const NSString* SEARCH_BAR_DID_SEARCH_NOTIFICATION = @"SEARCH_BAR_DID_SEARCH_NOTIFICATION";
const NSString* SEARCH_BAR_USER_INFO_QUERY_KEY = @"SEARCH_BAR_USER_INFO_QUERY_KEY";
const NSString* LOCATION_SEARCH_DID_END_EDITING_NOTIFICATION = @"LOCATION_SEARCH_DID_END_EDITING_NOTIFICATION";
const NSString* FILTER_BUTTON_REQUESTED_OPEN_NOTIFICATION = @"MENU_BUTTON_REQUESTED_OPEN_NOTIFICATION";
const NSString* MAP_BUTTON_REQUESTED_OPEN_NOTIFICATION = @"MAP_BUTTON_REQUESTED_OPEN_NOTIFICATION";
const NSString* PHOTO_WAS_SELECTED_NOTIFICATION= @"PHOTO_WAS_SELECTED_NOTIFICATION";
const NSString* LOAD_URL_REQUEST_NOTIFICATION= @"LOAD_URL_REQUEST_NOTIFICATION";

//
const NSString* CONNECTIVITY_ISSUE_NOTIFICATION= @"CONNECTIVITY_ISSUE_NOTIFICATION";
const NSString* LOCATION_ISSUE_NOTIFICATION= @"LOCATION_ISSUE_NOTIFICATION";
const NSString* SHARE_REQUEST_NOTIFICATION= @"SHARE_REQUEST_NOTIFICATION";

//
const NSString* NOPHOTO_IMAGE_PATH= @"no_image";
const NSString* BACKGROUND_IMAGE_PHOTO_PATH = @"green_gradient";

// User Info key paths
const NSString* USER_INFO_WEBSITE_URL_KEY= @"USER_INFO_WEBSITE_URL_KEY";

//
const NSString *ADMOB_ADVERTISING_KEY = @"XXX";
const NSString *TESTFLIGHT_KEY = @"XXXX";
const NSString *GOOGLE_ANALYTICS_KEY = @"XXX";

@end
